# Port na kojem Gateway radi
server.port=8085

# Definisanje rute ka backend aplikacijama
spring.cloud.gateway.routes[0].id=backend_route
spring.cloud.gateway.routes[0].uri=lb://backend-service
  #lb://backend-service   # lb:// koristi LoadBalancer
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

# Retry policy - retry 3 puta ako instanca ne odgovori
spring.cloud.gateway.routes[0].filters[0]=Retry=3

logging.level.org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory=TRACE
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.reactor.netty.http.client=DEBUG
logging.level.reactor.netty.resources=DEBUG
