{
 "title": "ISA - 3.20",
 "description": " Vizuelno prikazati sledeće metrike:\n ● prosečno trajanje HTTP zahteva za kreiranje nove objave u toku 24h\n ● prosečno zauzeće CPU u određenom vremenskom intervalu\n ● broj trenutno aktivnih korisnika u toku 24h",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Broj trenutno aktivnih korisnika u toku 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "active_users\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Prosečno zauzeće CPU u 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1h])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prosečno trajanje HTTP zahteva za kreiranje nove objave u toku 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/api/posts/create\", method=\"POST\"}[24h])\r\n/\r\nrate(http_server_requests_seconds_count{uri=\"/api/posts/create\", method=\"POST\"}[24h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}