springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.mail.host = smtp.gmail.com
spring.mail.username = isa.projekti@gmail.com
spring.mail.password = rvybjunymcsnzsbf
spring.mail.port=587
spring.mail.properties.mail.smtp.starttls.enable = true
spring.cache.jcache.config=classpath:ehcache.xml
spring.aop.proxy-target-class=true

#Spring DataSource drajver koji će se koristiti za komunikaciju aplikacije sa bazom
spring.datasource.driverClassName=org.postgresql.Driver

#Navodi se baza koja se koristi
spring.datasource.platform=postgres

#Navodi se URL do baze koja je pokrenuta u lokalu na podrazumevanom portu 5432 i na serveru je kreirana šema baze pod nazivom "jpa"
#https://www.pgadmin.org/docs/pgadmin4/4.14/schema_dialog.html (ako koristimo Hibernate za kreiranje tabela, SQL deo sa linka nije potreban)
spring.datasource.url=jdbc:postgresql://localhost:5432/onlybans

#Navode se kredencijali za konekciju na server baze
spring.datasource.username=postgres
spring.datasource.password=super

#Umesto da sami pišemo SQL skriptu za kreiranje tabela u bazi, Hibernate kreira tabele na osnovu anotacija @Entity i kada aplikacija zavrsi sa radom dropuje ih (create-drop)
#https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
#Ako želimo sami da kreiramo skriptu za kreiranje tabela potrebno je u src/main/resources folderu kreirati i popuniti fajl pod nazivom schema.sql koji će Spring Boot automatski pokrenuti pri pokretanju aplikacije
spring.jpa.hibernate.ddl-auto = update

#Hibernate SQL upiti se ispisuju na IDE konzoli
spring.jpa.show-sql = true

#formatira ispis SQL upita koje Hibernate pravi ka bazi na IDE konzoli
spring.jpa.properties.hibernate.format_sql=true

#https://docs.spring.io/spring-boot/docs/2.1.0.M1/reference/html/howto-database-initialization.html#howto-initialize-a-database-using-spring-jdbc
#spring.datasource.initialization-mode=always
spring.sql.init.mode=always

#https://stackoverflow.com/questions/43905119/postgres-error-method-org-postgresql-jdbc-pgconnection-createclob-is-not-imple
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#Hibernate optimizacija SQL upita za Postgres bazu
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL95Dialect

#https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
spring.jpa.open-in-view=false

spring.web.resources.static-locations=file:images/

#minimum number of idle connections maintained by HikariCP in a connection pool
spring.datasource.hikari.minimum-idle=5
#maximum pool size
spring.datasource.hikari.maximum-pool-size=20

spring.datasource.hikari.poolName=SpringBootJPAHikariCP

#maximum idle time for connection
spring.datasource.hikari.idle-timeout=30000
# maximum lifetime in milliseconds of a connection in the pool after it is closed.
spring.datasource.hikari.maxLifetime=2000000
#maximum number of milliseconds that a client will wait for a connection
spring.datasource.hikari.connectionTimeout=30000

# Enable logging to verify that HikariCP is used, the second entry is specific to HikariCP
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#max number of calls allowed within a specific time period
resilience4j.ratelimiter.instances.standard.limit-for-period=50
#specific time period - duration after which the rate limit counter is refreshed
resilience4j.ratelimiter.instances.standard.limit-refresh-period = 60s
# Maximum time allowed to wait for a permit if the limit is reached
resilience4j.ratelimiter.instances.standard.timeout-duration = 0
#


# Maksimalan broj poziva (dozvoljeno 5 poku?aja prijava sa jedne IP adrese)
resilience4j.ratelimiter.instances.login.limitForPeriod=5

# Vremenski interval za osve?avanje broja dozvoljenih poziva (1 minut)
resilience4j.ratelimiter.instances.login.limitRefreshPeriod=1m

# Vreme ?ekanja na odgovor (ako je limit dosegnut, nema ?ekanja, odmah se blokira)
resilience4j.ratelimiter.instances.login.timeoutDuration=0


# Enable logging to verify that HikariCP is used, the second entry is specific to HikariCP
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#RabbitMQ queue
myqueue=spring-boot1
routingkey=spring-boot1
myexchange=myexchange

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.enabled=true
rabbitmq.exchange=ads.exchange
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#Logovanje specifi?nih paketa
logging.level.rs.ac.uns.ftn.informatika.jpa.exception=DEBUG
logging.level.rs.ac.uns.ftn.informatika.jpa.service=DEBUG
logging.level.rs.ac.uns.ftn.informatika.jpa.service.impl=DEBUG
logging.level.rs.ac.uns.ftn.informatika.jpa.controller=DEBUG
logging.level.rs.ac.uns.ftn.informatika.jpa.validation=DEBUG
logging.level.rs.ac.uns.ftn.informatika.jpa.config.EhcacheConfig=INFO
# --- Hibernate debug OFF ---
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

# --- Globalni nivo logovanja za sve ostale (WARN i ERROR) ---
logging.level.root=INFO

# --- Logovanje u fajl ---
logging.file.name=logs/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n

# --- Format logova u konzoli (opciono) ---
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n

# --- Cron za ?i??enje ---
cleanup.cron=0 59 23 L * ?
